# Generated by Django 5.2.6 on 2025-09-24 21:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clientes', '0001_initial'),
        ('empleados', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Prestamo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto', models.DecimalField(decimal_places=2, max_digits=12)),
                ('monto_restante', models.DecimalField(decimal_places=2, max_digits=12)),
                ('descripcion', models.CharField(max_length=255)),
                ('interes', models.DecimalField(decimal_places=2, max_digits=5)),
                ('fecha_solicitud', models.DateField()),
                ('fecha_aprobacion', models.DateField(blank=True, null=True)),
                ('estado_aprobacion', models.BooleanField(default=False)),
                ('fecha_inicio', models.DateField(blank=True, null=True)),
                ('fecha_fin', models.DateField(blank=True, null=True)),
                ('frecuencia_pagos', models.IntegerField()),
                ('estado_pagos', models.CharField(blank=True, max_length=20, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prestamos', to='clientes.cliente')),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prestamos', to='empleados.empleado')),
            ],
            options={
                'db_table': 'prestamos',
            },
        ),
    ]
