# Generated by Django 5.2.6 on 2025-09-26 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Prestamo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto_aprobado', models.DecimalField(decimal_places=2, max_digits=12)),
                ('monto_restante', models.DecimalField(decimal_places=2, max_digits=12)),
                ('interes', models.DecimalField(decimal_places=2, max_digits=5)),
                ('fecha_desembolso', models.DateField(blank=True, null=True)),
                ('fecha_plazo', models.DateField(blank=True, null=True)),
                ('frecuencia_pagos', models.IntegerField()),
                ('estado', models.CharField(choices=[('En Curso', 'En Curso'), ('Mora', 'Mora'), ('Completado', 'Completado')], default='En Curso', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'prestamos',
            },
        ),
    ]
