# Generated by Django 5.2.6 on 2025-09-26 01:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('prestamos', '0001_initial'),
        ('solicitudes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='prestamo',
            name='solicitud',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='prestamo', to='solicitudes.solicitudprestamo'),
        ),
    ]
