# Generated by Django 5.2.6 on 2025-10-26 23:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('prestamos', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prestamo',
            name='frecuencia_pagos',
        ),
    ]
