# Generated by Django 5.2.6 on 2025-10-30 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prestamos', '0003_remove_prestamo_frecuencia_pagos'),
    ]

    operations = [
        migrations.AddField(
            model_name='prestamo',
            name='plazo_meses',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
