# Generated by Django 5.2.6 on 2025-10-30 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solicitudes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitudprestamo',
            name='plazo_meses',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
