# Generated by Django 5.2.6 on 2025-10-30 21:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('solicitudes', '0002_alter_solicitudprestamo_plazo_meses'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='solicitudprestamo',
            name='plazo_meses',
        ),
    ]
