# Generated by Django 5.2.6 on 2025-09-25 01:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('empleados', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='empleado',
            old_name='user_id',
            new_name='user',
        ),
    ]
