# Generated by Django 5.2.6 on 2025-10-21 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empleados', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empleado',
            name='apellido_materno',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='apellido_paterno',
            field=models.CharField(blank=True, max_length=45, null=True),
        ),
    ]
