# Generated by Django 5.2.6 on 2025-09-26 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('carnet', models.CharField(max_length=12, unique=True)),
                ('nombre', models.CharField(max_length=30)),
                ('apellido_paterno', models.CharField(max_length=30)),
                ('apellido_materno', models.CharField(max_length=30)),
                ('lugar_trabajo', models.CharField(max_length=60)),
                ('tipo_trabajo', models.CharField(max_length=30)),
                ('ingreso_mensual', models.DecimalField(decimal_places=2, max_digits=12)),
                ('direccion', models.CharField(max_length=255)),
                ('correo', models.CharField(blank=True, max_length=50, null=True)),
                ('telefono', models.BigIntegerField(unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'clientes',
            },
        ),
    ]
