# Generated by Django 5.2.6 on 2025-10-21 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0002_cliente_activo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='apellido_materno',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='apellido_paterno',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
