# Generated by Django 5.2.6 on 2025-10-26 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0004_cliente_complemento'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='cliente',
            constraint=models.UniqueConstraint(fields=('carnet', 'complemento'), name='unique_carnet_complemento'),
        ),
    ]
