# Generated by Django 5.2.6 on 2025-10-26 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0005_cliente_unique_carnet_complemento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='carnet',
            field=models.CharField(max_length=12),
        ),
    ]
