# Generated by Django 5.2.6 on 2025-09-24 21:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('prestamos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlanPago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_pago', models.DateField()),
                ('fecha_vencimiento', models.DateField()),
                ('metodo_pago', models.CharField(max_length=45)),
                ('monto_cuota', models.DecimalField(decimal_places=2, max_digits=12)),
                ('estado', models.CharField(max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('prestamo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='plan_pagos', to='prestamos.prestamo')),
            ],
            options={
                'db_table': 'plan_pagos',
            },
        ),
    ]
