# Generated by Django 5.2.6 on 2025-09-26 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PlanPago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_pago', models.DateField()),
                ('fecha_vencimiento', models.DateField()),
                ('metodo_pago', models.CharField(max_length=45)),
                ('monto_cuota', models.DecimalField(decimal_places=2, max_digits=12)),
                ('mora_cuota', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('estado', models.CharField(choices=[('Pendiente', 'Pendiente'), ('Pagada', 'Pagada'), ('Retraso', 'Retraso')], default='Pendiente', max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'plan_pagos',
            },
        ),
    ]
