# Generated by Django 5.2.6 on 2025-09-26 01:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('plan_pagos', '0001_initial'),
        ('prestamos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='planpago',
            name='prestamo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='plan_pagos', to='prestamos.prestamo'),
        ),
    ]
