# Generated by Django 5.2.6 on 2025-09-30 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plan_pagos', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='planpago',
            name='fecha_pago',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='planpago',
            name='metodo_pago',
            field=models.CharField(blank=True, max_length=45, null=True),
        ),
    ]
