# Generated by Django 5.2.6 on 2025-09-24 21:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('prestamos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Documento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_documento', models.CharField(max_length=30)),
                ('archivo', models.JSONField(blank=True, null=True)),
                ('verificado', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('prestamo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='documentos', to='prestamos.prestamo')),
            ],
            options={
                'db_table': 'documentos',
            },
        ),
    ]
