# Generated by Django 5.2.6 on 2025-10-31 00:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documentos', '0003_alter_documento_solicitud'),
        ('solicitudes', '0003_remove_solicitudprestamo_plazo_meses'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documento',
            name='solicitud',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='documentos', to='solicitudes.solicitudprestamo'),
        ),
    ]
