# Generated by Django 5.2.6 on 2025-12-01 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auditoria', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditoria',
            name='accion',
            field=models.CharField(choices=[('REGISTRO', 'Registro'), ('ACTUALIZACIÓN', 'Actualización'), ('ELIMINACIÓN', 'Eliminación'), ('INICIO DE SESIÓN', 'Inicio de sesión'), ('CIERRE DE SESIÓN', 'Cierre de sesión')], max_length=20),
        ),
    ]
